---
name: code-quality
on:
  push:
    branches: [main]
  pull_request_target:
  workflow_dispatch:
jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Spell Check
        # https://github.com/crate-ci/typos
        uses: crate-ci/typos@master
      - name: Shell and shfmt Check
        # https://github.com/luizm/action-sh-checker
        uses: luizm/action-sh-checker@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHFMT_OPTS: --simplify --indent 4 --case-indent
        with:
          sh_checker_comment: true
