---
name: code-quality
on:
  push:
    branches: [main]
  pull_request_target:
  workflow_dispatch:
jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: crate-ci/typos@master
      - uses: luizm/action-sh-checker@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHFMT_OPTS: --simplify --indent 2 --case-indent
        with:
          sh_checker_comment: true
